### PR TITLE
moved fix.js into the component already in main, PR to fix the render…

### PR DESCRIPTION
**Pull request by josmo**
Once https://github.com/studiointeract/accounts-ui/pull/124 gets merged it, it should no longer need the issue #18 fix.  This with that PR should make the accounts-meterial-ui work with the latest std:accounts-ui :)

### CODE REVIEW

**Comment by josmo** [comment]
oh @PolGuixe I also, moved the Field fix in main. It seemed a little easier to reason about what was going on :)

**Comment by PolGuixe** [comment]
@josmo excellent work. Let me know when https://github.com/studiointeract/accounts-ui/pull/124
gets merged.

**Comment by yanickrochon** [comment]
Will this be merged?

**Comment by PolGuixe** [comment]
@yanickrochon I am trying to move get the confirmation of @timbrandin to merge studiointeract/accounts-ui#124 and publish it.

**Pull request closed without merging**
